package mall.pojo;

public class CmsSubjectProductRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject_product_relation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject_product_relation.subject_id
     *
     * @mbg.generated
     */
    private Long subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject_product_relation.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject_product_relation
     *
     * @mbg.generated
     */
    public CmsSubjectProductRelation(Long id, Long subjectId, Long productId) {
        this.id = id;
        this.subjectId = subjectId;
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject_product_relation
     *
     * @mbg.generated
     */
    public CmsSubjectProductRelation() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject_product_relation.id
     *
     * @return the value of cms_subject_product_relation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject_product_relation.id
     *
     * @param id the value for cms_subject_product_relation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject_product_relation.subject_id
     *
     * @return the value of cms_subject_product_relation.subject_id
     *
     * @mbg.generated
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject_product_relation.subject_id
     *
     * @param subjectId the value for cms_subject_product_relation.subject_id
     *
     * @mbg.generated
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject_product_relation.product_id
     *
     * @return the value of cms_subject_product_relation.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject_product_relation.product_id
     *
     * @param productId the value for cms_subject_product_relation.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }
}