package mall.pojo;

import java.util.Date;

public class CmsSubjectComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject_comment.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject_comment.subject_id
     *
     * @mbg.generated
     */
    private Long subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject_comment.member_nick_name
     *
     * @mbg.generated
     */
    private String memberNickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject_comment.member_icon
     *
     * @mbg.generated
     */
    private String memberIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject_comment.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject_comment.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject_comment.show_status
     *
     * @mbg.generated
     */
    private Integer showStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject_comment
     *
     * @mbg.generated
     */
    public CmsSubjectComment(Long id, Long subjectId, String memberNickName, String memberIcon, String content, Date createTime, Integer showStatus) {
        this.id = id;
        this.subjectId = subjectId;
        this.memberNickName = memberNickName;
        this.memberIcon = memberIcon;
        this.content = content;
        this.createTime = createTime;
        this.showStatus = showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject_comment
     *
     * @mbg.generated
     */
    public CmsSubjectComment() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject_comment.id
     *
     * @return the value of cms_subject_comment.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject_comment.id
     *
     * @param id the value for cms_subject_comment.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject_comment.subject_id
     *
     * @return the value of cms_subject_comment.subject_id
     *
     * @mbg.generated
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject_comment.subject_id
     *
     * @param subjectId the value for cms_subject_comment.subject_id
     *
     * @mbg.generated
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject_comment.member_nick_name
     *
     * @return the value of cms_subject_comment.member_nick_name
     *
     * @mbg.generated
     */
    public String getMemberNickName() {
        return memberNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject_comment.member_nick_name
     *
     * @param memberNickName the value for cms_subject_comment.member_nick_name
     *
     * @mbg.generated
     */
    public void setMemberNickName(String memberNickName) {
        this.memberNickName = memberNickName == null ? null : memberNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject_comment.member_icon
     *
     * @return the value of cms_subject_comment.member_icon
     *
     * @mbg.generated
     */
    public String getMemberIcon() {
        return memberIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject_comment.member_icon
     *
     * @param memberIcon the value for cms_subject_comment.member_icon
     *
     * @mbg.generated
     */
    public void setMemberIcon(String memberIcon) {
        this.memberIcon = memberIcon == null ? null : memberIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject_comment.content
     *
     * @return the value of cms_subject_comment.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject_comment.content
     *
     * @param content the value for cms_subject_comment.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject_comment.create_time
     *
     * @return the value of cms_subject_comment.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject_comment.create_time
     *
     * @param createTime the value for cms_subject_comment.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject_comment.show_status
     *
     * @return the value of cms_subject_comment.show_status
     *
     * @mbg.generated
     */
    public Integer getShowStatus() {
        return showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject_comment.show_status
     *
     * @param showStatus the value for cms_subject_comment.show_status
     *
     * @mbg.generated
     */
    public void setShowStatus(Integer showStatus) {
        this.showStatus = showStatus;
    }
}