package mall.pojo;

import java.util.Date;

public class CmsTopic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic.attend_count
     *
     * @mbg.generated
     */
    private Integer attendCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic.attention_count
     *
     * @mbg.generated
     */
    private Integer attentionCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic.read_count
     *
     * @mbg.generated
     */
    private Integer readCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic.award_name
     *
     * @mbg.generated
     */
    private String awardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic.attend_type
     *
     * @mbg.generated
     */
    private String attendType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    public CmsTopic(Long id, Long categoryId, String name, Date createTime, Date startTime, Date endTime, Integer attendCount, Integer attentionCount, Integer readCount, String awardName, String attendType, String content) {
        this.id = id;
        this.categoryId = categoryId;
        this.name = name;
        this.createTime = createTime;
        this.startTime = startTime;
        this.endTime = endTime;
        this.attendCount = attendCount;
        this.attentionCount = attentionCount;
        this.readCount = readCount;
        this.awardName = awardName;
        this.attendType = attendType;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    public CmsTopic() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic.id
     *
     * @return the value of cms_topic.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic.id
     *
     * @param id the value for cms_topic.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic.category_id
     *
     * @return the value of cms_topic.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic.category_id
     *
     * @param categoryId the value for cms_topic.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic.name
     *
     * @return the value of cms_topic.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic.name
     *
     * @param name the value for cms_topic.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic.create_time
     *
     * @return the value of cms_topic.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic.create_time
     *
     * @param createTime the value for cms_topic.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic.start_time
     *
     * @return the value of cms_topic.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic.start_time
     *
     * @param startTime the value for cms_topic.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic.end_time
     *
     * @return the value of cms_topic.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic.end_time
     *
     * @param endTime the value for cms_topic.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic.attend_count
     *
     * @return the value of cms_topic.attend_count
     *
     * @mbg.generated
     */
    public Integer getAttendCount() {
        return attendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic.attend_count
     *
     * @param attendCount the value for cms_topic.attend_count
     *
     * @mbg.generated
     */
    public void setAttendCount(Integer attendCount) {
        this.attendCount = attendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic.attention_count
     *
     * @return the value of cms_topic.attention_count
     *
     * @mbg.generated
     */
    public Integer getAttentionCount() {
        return attentionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic.attention_count
     *
     * @param attentionCount the value for cms_topic.attention_count
     *
     * @mbg.generated
     */
    public void setAttentionCount(Integer attentionCount) {
        this.attentionCount = attentionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic.read_count
     *
     * @return the value of cms_topic.read_count
     *
     * @mbg.generated
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic.read_count
     *
     * @param readCount the value for cms_topic.read_count
     *
     * @mbg.generated
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic.award_name
     *
     * @return the value of cms_topic.award_name
     *
     * @mbg.generated
     */
    public String getAwardName() {
        return awardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic.award_name
     *
     * @param awardName the value for cms_topic.award_name
     *
     * @mbg.generated
     */
    public void setAwardName(String awardName) {
        this.awardName = awardName == null ? null : awardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic.attend_type
     *
     * @return the value of cms_topic.attend_type
     *
     * @mbg.generated
     */
    public String getAttendType() {
        return attendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic.attend_type
     *
     * @param attendType the value for cms_topic.attend_type
     *
     * @mbg.generated
     */
    public void setAttendType(String attendType) {
        this.attendType = attendType == null ? null : attendType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic.content
     *
     * @return the value of cms_topic.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic.content
     *
     * @param content the value for cms_topic.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}