package mall.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class OmsOrderReturnApply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.company_address_id
     *
     * @mbg.generated
     */
    private Long companyAddressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.order_sn
     *
     * @mbg.generated
     */
    private String orderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.member_username
     *
     * @mbg.generated
     */
    private String memberUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.return_amount
     *
     * @mbg.generated
     */
    private BigDecimal returnAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.return_name
     *
     * @mbg.generated
     */
    private String returnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.return_phone
     *
     * @mbg.generated
     */
    private String returnPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.handle_time
     *
     * @mbg.generated
     */
    private Date handleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.product_pic
     *
     * @mbg.generated
     */
    private String productPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.product_brand
     *
     * @mbg.generated
     */
    private String productBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.product_attr
     *
     * @mbg.generated
     */
    private String productAttr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.product_count
     *
     * @mbg.generated
     */
    private Integer productCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.product_price
     *
     * @mbg.generated
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.product_real_price
     *
     * @mbg.generated
     */
    private BigDecimal productRealPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.proof_pics
     *
     * @mbg.generated
     */
    private String proofPics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.handle_note
     *
     * @mbg.generated
     */
    private String handleNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.handle_man
     *
     * @mbg.generated
     */
    private String handleMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.receive_man
     *
     * @mbg.generated
     */
    private String receiveMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.receive_time
     *
     * @mbg.generated
     */
    private Date receiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_return_apply.receive_note
     *
     * @mbg.generated
     */
    private String receiveNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbg.generated
     */
    public OmsOrderReturnApply(Long id, Long orderId, Long companyAddressId, Long productId, String orderSn, Date createTime, String memberUsername, BigDecimal returnAmount, String returnName, String returnPhone, Integer status, Date handleTime, String productPic, String productName, String productBrand, String productAttr, Integer productCount, BigDecimal productPrice, BigDecimal productRealPrice, String reason, String description, String proofPics, String handleNote, String handleMan, String receiveMan, Date receiveTime, String receiveNote) {
        this.id = id;
        this.orderId = orderId;
        this.companyAddressId = companyAddressId;
        this.productId = productId;
        this.orderSn = orderSn;
        this.createTime = createTime;
        this.memberUsername = memberUsername;
        this.returnAmount = returnAmount;
        this.returnName = returnName;
        this.returnPhone = returnPhone;
        this.status = status;
        this.handleTime = handleTime;
        this.productPic = productPic;
        this.productName = productName;
        this.productBrand = productBrand;
        this.productAttr = productAttr;
        this.productCount = productCount;
        this.productPrice = productPrice;
        this.productRealPrice = productRealPrice;
        this.reason = reason;
        this.description = description;
        this.proofPics = proofPics;
        this.handleNote = handleNote;
        this.handleMan = handleMan;
        this.receiveMan = receiveMan;
        this.receiveTime = receiveTime;
        this.receiveNote = receiveNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbg.generated
     */
    public OmsOrderReturnApply() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.id
     *
     * @return the value of oms_order_return_apply.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.id
     *
     * @param id the value for oms_order_return_apply.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.order_id
     *
     * @return the value of oms_order_return_apply.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.order_id
     *
     * @param orderId the value for oms_order_return_apply.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.company_address_id
     *
     * @return the value of oms_order_return_apply.company_address_id
     *
     * @mbg.generated
     */
    public Long getCompanyAddressId() {
        return companyAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.company_address_id
     *
     * @param companyAddressId the value for oms_order_return_apply.company_address_id
     *
     * @mbg.generated
     */
    public void setCompanyAddressId(Long companyAddressId) {
        this.companyAddressId = companyAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.product_id
     *
     * @return the value of oms_order_return_apply.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.product_id
     *
     * @param productId the value for oms_order_return_apply.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.order_sn
     *
     * @return the value of oms_order_return_apply.order_sn
     *
     * @mbg.generated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.order_sn
     *
     * @param orderSn the value for oms_order_return_apply.order_sn
     *
     * @mbg.generated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.create_time
     *
     * @return the value of oms_order_return_apply.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.create_time
     *
     * @param createTime the value for oms_order_return_apply.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.member_username
     *
     * @return the value of oms_order_return_apply.member_username
     *
     * @mbg.generated
     */
    public String getMemberUsername() {
        return memberUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.member_username
     *
     * @param memberUsername the value for oms_order_return_apply.member_username
     *
     * @mbg.generated
     */
    public void setMemberUsername(String memberUsername) {
        this.memberUsername = memberUsername == null ? null : memberUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.return_amount
     *
     * @return the value of oms_order_return_apply.return_amount
     *
     * @mbg.generated
     */
    public BigDecimal getReturnAmount() {
        return returnAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.return_amount
     *
     * @param returnAmount the value for oms_order_return_apply.return_amount
     *
     * @mbg.generated
     */
    public void setReturnAmount(BigDecimal returnAmount) {
        this.returnAmount = returnAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.return_name
     *
     * @return the value of oms_order_return_apply.return_name
     *
     * @mbg.generated
     */
    public String getReturnName() {
        return returnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.return_name
     *
     * @param returnName the value for oms_order_return_apply.return_name
     *
     * @mbg.generated
     */
    public void setReturnName(String returnName) {
        this.returnName = returnName == null ? null : returnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.return_phone
     *
     * @return the value of oms_order_return_apply.return_phone
     *
     * @mbg.generated
     */
    public String getReturnPhone() {
        return returnPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.return_phone
     *
     * @param returnPhone the value for oms_order_return_apply.return_phone
     *
     * @mbg.generated
     */
    public void setReturnPhone(String returnPhone) {
        this.returnPhone = returnPhone == null ? null : returnPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.status
     *
     * @return the value of oms_order_return_apply.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.status
     *
     * @param status the value for oms_order_return_apply.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.handle_time
     *
     * @return the value of oms_order_return_apply.handle_time
     *
     * @mbg.generated
     */
    public Date getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.handle_time
     *
     * @param handleTime the value for oms_order_return_apply.handle_time
     *
     * @mbg.generated
     */
    public void setHandleTime(Date handleTime) {
        this.handleTime = handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.product_pic
     *
     * @return the value of oms_order_return_apply.product_pic
     *
     * @mbg.generated
     */
    public String getProductPic() {
        return productPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.product_pic
     *
     * @param productPic the value for oms_order_return_apply.product_pic
     *
     * @mbg.generated
     */
    public void setProductPic(String productPic) {
        this.productPic = productPic == null ? null : productPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.product_name
     *
     * @return the value of oms_order_return_apply.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.product_name
     *
     * @param productName the value for oms_order_return_apply.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.product_brand
     *
     * @return the value of oms_order_return_apply.product_brand
     *
     * @mbg.generated
     */
    public String getProductBrand() {
        return productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.product_brand
     *
     * @param productBrand the value for oms_order_return_apply.product_brand
     *
     * @mbg.generated
     */
    public void setProductBrand(String productBrand) {
        this.productBrand = productBrand == null ? null : productBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.product_attr
     *
     * @return the value of oms_order_return_apply.product_attr
     *
     * @mbg.generated
     */
    public String getProductAttr() {
        return productAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.product_attr
     *
     * @param productAttr the value for oms_order_return_apply.product_attr
     *
     * @mbg.generated
     */
    public void setProductAttr(String productAttr) {
        this.productAttr = productAttr == null ? null : productAttr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.product_count
     *
     * @return the value of oms_order_return_apply.product_count
     *
     * @mbg.generated
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.product_count
     *
     * @param productCount the value for oms_order_return_apply.product_count
     *
     * @mbg.generated
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.product_price
     *
     * @return the value of oms_order_return_apply.product_price
     *
     * @mbg.generated
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.product_price
     *
     * @param productPrice the value for oms_order_return_apply.product_price
     *
     * @mbg.generated
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.product_real_price
     *
     * @return the value of oms_order_return_apply.product_real_price
     *
     * @mbg.generated
     */
    public BigDecimal getProductRealPrice() {
        return productRealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.product_real_price
     *
     * @param productRealPrice the value for oms_order_return_apply.product_real_price
     *
     * @mbg.generated
     */
    public void setProductRealPrice(BigDecimal productRealPrice) {
        this.productRealPrice = productRealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.reason
     *
     * @return the value of oms_order_return_apply.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.reason
     *
     * @param reason the value for oms_order_return_apply.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.description
     *
     * @return the value of oms_order_return_apply.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.description
     *
     * @param description the value for oms_order_return_apply.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.proof_pics
     *
     * @return the value of oms_order_return_apply.proof_pics
     *
     * @mbg.generated
     */
    public String getProofPics() {
        return proofPics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.proof_pics
     *
     * @param proofPics the value for oms_order_return_apply.proof_pics
     *
     * @mbg.generated
     */
    public void setProofPics(String proofPics) {
        this.proofPics = proofPics == null ? null : proofPics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.handle_note
     *
     * @return the value of oms_order_return_apply.handle_note
     *
     * @mbg.generated
     */
    public String getHandleNote() {
        return handleNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.handle_note
     *
     * @param handleNote the value for oms_order_return_apply.handle_note
     *
     * @mbg.generated
     */
    public void setHandleNote(String handleNote) {
        this.handleNote = handleNote == null ? null : handleNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.handle_man
     *
     * @return the value of oms_order_return_apply.handle_man
     *
     * @mbg.generated
     */
    public String getHandleMan() {
        return handleMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.handle_man
     *
     * @param handleMan the value for oms_order_return_apply.handle_man
     *
     * @mbg.generated
     */
    public void setHandleMan(String handleMan) {
        this.handleMan = handleMan == null ? null : handleMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.receive_man
     *
     * @return the value of oms_order_return_apply.receive_man
     *
     * @mbg.generated
     */
    public String getReceiveMan() {
        return receiveMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.receive_man
     *
     * @param receiveMan the value for oms_order_return_apply.receive_man
     *
     * @mbg.generated
     */
    public void setReceiveMan(String receiveMan) {
        this.receiveMan = receiveMan == null ? null : receiveMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.receive_time
     *
     * @return the value of oms_order_return_apply.receive_time
     *
     * @mbg.generated
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.receive_time
     *
     * @param receiveTime the value for oms_order_return_apply.receive_time
     *
     * @mbg.generated
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_return_apply.receive_note
     *
     * @return the value of oms_order_return_apply.receive_note
     *
     * @mbg.generated
     */
    public String getReceiveNote() {
        return receiveNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_return_apply.receive_note
     *
     * @param receiveNote the value for oms_order_return_apply.receive_note
     *
     * @mbg.generated
     */
    public void setReceiveNote(String receiveNote) {
        this.receiveNote = receiveNote == null ? null : receiveNote.trim();
    }
}