package mall.pojo;

public class PmsAlbum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_album.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_album.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_album.cover_pic
     *
     * @mbg.generated
     */
    private String coverPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_album.pic_count
     *
     * @mbg.generated
     */
    private Integer picCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_album.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_album.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbg.generated
     */
    public PmsAlbum(Long id, String name, String coverPic, Integer picCount, Integer sort, String description) {
        this.id = id;
        this.name = name;
        this.coverPic = coverPic;
        this.picCount = picCount;
        this.sort = sort;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbg.generated
     */
    public PmsAlbum() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_album.id
     *
     * @return the value of pms_album.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_album.id
     *
     * @param id the value for pms_album.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_album.name
     *
     * @return the value of pms_album.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_album.name
     *
     * @param name the value for pms_album.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_album.cover_pic
     *
     * @return the value of pms_album.cover_pic
     *
     * @mbg.generated
     */
    public String getCoverPic() {
        return coverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_album.cover_pic
     *
     * @param coverPic the value for pms_album.cover_pic
     *
     * @mbg.generated
     */
    public void setCoverPic(String coverPic) {
        this.coverPic = coverPic == null ? null : coverPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_album.pic_count
     *
     * @return the value of pms_album.pic_count
     *
     * @mbg.generated
     */
    public Integer getPicCount() {
        return picCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_album.pic_count
     *
     * @param picCount the value for pms_album.pic_count
     *
     * @mbg.generated
     */
    public void setPicCount(Integer picCount) {
        this.picCount = picCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_album.sort
     *
     * @return the value of pms_album.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_album.sort
     *
     * @param sort the value for pms_album.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_album.description
     *
     * @return the value of pms_album.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_album.description
     *
     * @param description the value for pms_album.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}