package mall.mapper;

import java.util.List;
import mall.pojo.CmsHelp;
import mall.pojo.CmsHelpExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CmsHelpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     */
    long countByExample(CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     */
    int deleteByExample(CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     */
    int insert(CmsHelp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     */
    int insertSelective(CmsHelp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     */
    List<CmsHelp> selectByExampleWithBLOBsWithRowbounds(CmsHelpExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     */
    List<CmsHelp> selectByExampleWithBLOBs(CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     */
    List<CmsHelp> selectByExampleWithRowbounds(CmsHelpExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     */
    List<CmsHelp> selectByExample(CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     */
    CmsHelp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmsHelp record, @Param("example") CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") CmsHelp record, @Param("example") CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmsHelp record, @Param("example") CmsHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsHelp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CmsHelp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_help
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsHelp record);
}