package mall.mapper;

import java.util.List;
import mall.pojo.CmsTopic;
import mall.pojo.CmsTopicExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CmsTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    long countByExample(CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int deleteByExample(CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int insert(CmsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int insertSelective(CmsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    List<CmsTopic> selectByExampleWithBLOBsWithRowbounds(CmsTopicExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    List<CmsTopic> selectByExampleWithBLOBs(CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    List<CmsTopic> selectByExampleWithRowbounds(CmsTopicExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    List<CmsTopic> selectByExample(CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    CmsTopic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmsTopic record, @Param("example") CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") CmsTopic record, @Param("example") CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmsTopic record, @Param("example") CmsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CmsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsTopic record);
}